### PR TITLE
Mocap integration

### PR DESCRIPTION
**Pull request by bhairavmehta95**

### CODE REVIEW

**Comment by bhairavmehta95** [comment]
In preparation for integration meeting tomorrow.

**Comment by bhairavmehta95** [comment]
Last few changes: fixed weird slide issue (http://www.mujoco.org/forum/index.php?threads/slide-joints.3597/)

**Review by ethanabrooks — APPROVED** [review]

**Comment by bhairavmehta95** [comment]
Just got back from vacation, can fix the conflict and merge today.

**Comment by ethanabrooks** [comment]
Ah no hurry. So Satinder is pushing me toward higher dimensional stuff, and
once that's the case, I'll start using mocap.

**Pull request merged**
